### PR TITLE
Add tests for Redux actions

### PR DESCRIPTION
**Pull request by jonmast**
Add rudimentary tests for all our action creators. This required moving the actual dispatches to the components and switching the asynchronous ones to use redux-thunk.

### CODE REVIEW

**Comment by ciacci1234** [comment]
I haven't really touched React code since the conclusion of the Launchpad month, so at this point in time, I can't in good faith approve this PR. I'm hoping @aaronclong can handle this one, however, I will also try to dive back into the React world, so that I could give this a meaningful review.

Without knowing the specifics of these changes, it seems like a lot of changes in order to make tests happen. Just to confirm, all changes made were to successfully create tests or were there other reasons? This question arose for me when I was looking at the changes to `tokens.js` for example.

This is just my initial impression after briefly looking through the changes, but as I mentioned, I'd like to do a more thorough review after reacclimating myself to React, if Aaron doesn't get to it that is 👌

**Comment by jonmast** [comment]
@ciacci1234 All of the changes were made in the process of writing tests, but I made a few changes to other things while I was updating the code. In your specific example of the tokens file, I did that to make a test pass, but after some checking I realized that this was because I was using my editor TDD integration and that wasn't setting up the ENV vars. The bit I removed there doesn't do anything on my machine since the token doesn't contain those characters, I think it is unnecessary. I can add it back in if you think we still need it.

To your point about this being a lot of changes just to get tests passing, let me explain that a bit. The way the actions were originally written is to import the Redux store and call the `dispatch` method on it, passing in the action object. The testing docs I was looking at had the action functions simply return the action object (or a function for the redux-thunk async) ones, which allowed them to use a fake store in the test file. I didn't know of any way to test it using our original design, so I decided to switch to using the method shown in the docs. This meant that we needed to have the `dispatch` function available in every component that dispatches an action, this is why all the extra `connect` code was needed. I also needed to make a few changes in some actions to ensure that a promise was returned so that the test waited until the asynchronous request completed to check for the result.

**Comment by jonmast** [comment]
Looking over the diff again, I see that the first commit actually has nothing to do with adding tests, it adds proptypes to some components. I think I had originally planned on working on that, but then decided to add tests instead for some reason.

**Comment by ciacci1234** [comment]
Okay, appreciate your explanation 💯  I believe I understand the changes, and my gut instinct is that they are fine and merge-able, but I think I'll hold off and see if @aaronclong can take a look at them, just to be  on the safe side 👌  At least until I feel more comfortable with React code, which I'm hoping to spend some time on this weekend.

**Pull request merged**
