### PR TITLE
Add additional years of US House districts

### PR DESCRIPTION
**Pull request by jonmast**
Add some historical data on PA US House districts.

Note: PA had more house districts in previous years, this causes no stats data to be displayed when a higher numbered district is clicked. The districts also sometimes move around the state, we need to think
about effective ways to communicate this to the user.

### CODE REVIEW

**Comment by ciacci1234** [comment]
>PA had more house districts in previous years, this causes no stats data to be displayed when a higher numbered district is clicked. 

Do you think there is a way around this or is this unavoidable behavior? When I was exploring your branch locally, this seemed like a significant enough problem to warrant finding a solution to it before merging the branch's changes into master. That's just my opinion though. Do you think it would be better to merge this in and then open an issue about this problem? Also, @aaronclong, your thoughts on this are welcome as well!

**Comment by jonmast** [comment]
@ciacci1234 What would you expect to happen in this scenario? The best solution I know of would be to only show the election data for the latest year, since that is all it really relevant for. Unfortunately, we also use the stats data for the district name, it would take a bit of work to allow us to still display that.

**Comment by ciacci1234** [comment]
So my current understanding of your comments is that in previous years, there are a higher number of districts and the current data we have to create statistics does not encompass these older years, and as a result, nothing on the map is displayed. Is this correct?

The intended behavior I'd hope for is when I click on this district-from 1991, the top left most district on the map-for example:
screen shot 2017-08-22 at 11 42 27 pm

I would like to see the stats like we do for other districts. Would this be possible? Do we need to collect more data to do this? Or does that data not exist?

**Comment by jonmast** [comment]
What stats would you expect to see? For the other districts we show the results from the 2016 election, but since that district didn't exist then we can't show the stats. The fact is, even the stats we do show for historical data might be totally worthless if the district moved, since it isn't really the same district anymore.

A possible solution would be to show older election data for the historical districts. We'd need to figure out which election year to match to which redistricting year and how to communicate this effectively though. Also, our current source of data only goes back to 2000, I don't know if it is possible at all to get data for before then.

We should be able to show the district name and compactness score for any district, we could just show that and skip the election data for older years. This would require some modifications to our data since we currently store the district name alongside the election stats, but there is no technical reason it wouldn't work.

**Comment by ciacci1234** [comment]
Ah, I think understand now. I didn't realize that we were showing 2016 results of the election regardless of what year we were looking at. This seems to be true for the PA House and Senate views as well. Is my understanding correct?

I had assumed each year displayed on the map corresponded with an election. So I suppose my issue with your changes is not really about your changes, but instead what we are currently displaying on the map. I think I'd like to take this conversation with you offline to discuss this a bit further. Look out for a slack message from me about making this happen 👌

**Comment by jonmast** [comment]
@ciacci1234 Correct, except that half of the Senate results are from 2014 since PA elects senators to 4 year terms and staggers the elections.

We had originally planned to show historical election data with the historical maps, but since there isn't a one to one mapping between redistricting years and election years it turned out to be a bit complicated. We ended up just going with the latest data in the interest of simplicity as we were crunching for demo night.

Having an offline conversation is a great idea, there are lots of details to work through 👍

**Pull request merged**
